-- MTG Beta Card Lists for Project Zomboid
-- Auto-generated from Scryfall API

beta_c = {
    "mtgcards.benalish-hero-4",
    "mtgcards.blue-elemental-blast-50",
    "mtgcards.circle-of-protection-black-10",
    "mtgcards.circle-of-protection-blue-11",
    "mtgcards.circle-of-protection-green-12",
    "mtgcards.circle-of-protection-red-13",
    "mtgcards.circle-of-protection-white-14",
    "mtgcards.craw-wurm-191",
    "mtgcards.creature-bond-56",
    "mtgcards.dark-ritual-99",
    "mtgcards.death-ward-18",
    "mtgcards.disenchant-19",
    "mtgcards.disintegrate-141",
    "mtgcards.drain-life-106",
    "mtgcards.drudge-skeletons-107",
    "mtgcards.dwarven-warriors-144",
    "mtgcards.earthbind-146",
    "mtgcards.false-orders-148",
    "mtgcards.fear-109",
    "mtgcards.fireball-150",
    "mtgcards.firebreathing-151",
    "mtgcards.flight-59",
    "mtgcards.fog-194",
    "mtgcards.frozen-shade-110",
    "mtgcards.giant-growth-198",
    "mtgcards.giant-spider-199",
    "mtgcards.gray-ogre-157",
    "mtgcards.grizzly-bears-200",
    "mtgcards.guardian-angel-22",
    "mtgcards.healing-salve-23",
    "mtgcards.hill-giant-158",
    "mtgcards.holy-armor-24",
    "mtgcards.holy-strength-25",
    "mtgcards.howl-from-beyond-112",
    "mtgcards.hurloon-minotaur-159",
    "mtgcards.invisibility-60",
    "mtgcards.ironclaw-orcs-160",
    "mtgcards.ironroot-treefolk-204",
    "mtgcards.jump-61",
    "mtgcards.lightning-bolt-162",
    "mtgcards.llanowar-elves-211",
    "mtgcards.merfolk-of-the-pearl-trident-67",
    "mtgcards.mesa-pegasus-29",
    "mtgcards.monss-goblin-raiders-165",
    "mtgcards.paralyze-120",
    "mtgcards.pearled-unicorn-31",
    "mtgcards.pestilence-121",
    "mtgcards.phantasmal-terrain-69",
    "mtgcards.plague-rats-122",
    "mtgcards.power-leak-72",
    "mtgcards.power-sink-73",
    "mtgcards.prodigal-sorcerer-74",
    "mtgcards.psychic-venom-76",
    "mtgcards.raise-dead-123",
    "mtgcards.red-elemental-blast-170",
    "mtgcards.regeneration-214",
    "mtgcards.samite-healer-38",
    "mtgcards.scathe-zombies-126",
    "mtgcards.scryb-sprites-216",
    "mtgcards.sea-serpent-77",
    "mtgcards.shanodin-dryads-217",
    "mtgcards.shatter-174",
    "mtgcards.sinkhole-130",
    "mtgcards.spell-blast-80",
    "mtgcards.stone-rain-178",
    "mtgcards.stream-of-life-218",
    "mtgcards.terror-131",
    "mtgcards.tranquility-221",
    "mtgcards.twiddle-86",
    "mtgcards.unholy-strength-132",
    "mtgcards.unsummon-87",
    "mtgcards.wall-of-wood-226",
    "mtgcards.war-mammoth-228",
    "mtgcards.weakness-135",
    "mtgcards.wild-growth-230",
}

beta_u = {
    "mtgcards.air-elemental-47",
    "mtgcards.animate-artifact-49",
    "mtgcards.animate-dead-93",
    "mtgcards.basalt-monolith-232",
    "mtgcards.berserk-186",
    "mtgcards.black-knight-95",
    "mtgcards.black-vise-234",
    "mtgcards.black-ward-5",
    "mtgcards.blue-ward-8",
    "mtgcards.bog-wraith-96",
    "mtgcards.burrowing-139",
    "mtgcards.camouflage-188",
    "mtgcards.castle-9",
    "mtgcards.celestial-prism-235",
    "mtgcards.channel-189",
    "mtgcards.clone-52",
    "mtgcards.consecrate-land-15",
    "mtgcards.conservator-238",
    "mtgcards.control-magic-53",
    "mtgcards.conversion-16",
    "mtgcards.copper-tablet-239",
    "mtgcards.counterspell-55",
    "mtgcards.crystal-rod-240",
    "mtgcards.cursed-land-98",
    "mtgcards.deathgrip-101",
    "mtgcards.demonic-tutor-105",
    "mtgcards.dragon-whelp-142",
    "mtgcards.dwarven-demolition-team-143",
    "mtgcards.earth-elemental-145",
    "mtgcards.evil-presence-108",
    "mtgcards.feedback-58",
    "mtgcards.fire-elemental-149",
    "mtgcards.flashfires-152",
    "mtgcards.glasses-of-urza-246",
    "mtgcards.gloom-111",
    "mtgcards.goblin-balloon-brigade-154",
    "mtgcards.green-ward-21",
    "mtgcards.hurricane-201",
    "mtgcards.hypnotic-specter-113",
    "mtgcards.ice-storm-202",
    "mtgcards.icy-manipulator-249",
    "mtgcards.instill-energy-203",
    "mtgcards.iron-star-251",
    "mtgcards.ivory-cup-252",
    "mtgcards.jade-statue-254",
    "mtgcards.juggernaut-256",
    "mtgcards.karma-27",
    "mtgcards.keldon-warlord-161",
    "mtgcards.lance-28",
    "mtgcards.ley-druid-206",
    "mtgcards.library-of-leng-258",
    "mtgcards.lifeforce-207",
    "mtgcards.lifetap-62",
    "mtgcards.living-wall-259",
    "mtgcards.lure-212",
    "mtgcards.nettling-imp-118",
    "mtgcards.obsianus-golem-268",
    "mtgcards.orcish-artillery-166",
    "mtgcards.orcish-oriflamme-167",
    "mtgcards.phantasmal-forces-68",
    "mtgcards.phantom-monster-70",
    "mtgcards.psionic-blast-75",
    "mtgcards.red-ward-34",
    "mtgcards.regrowth-215",
    "mtgcards.resurrection-35",
    "mtgcards.rod-of-ruin-269",
    "mtgcards.sacrifice-125",
    "mtgcards.scavenging-ghoul-127",
    "mtgcards.sengir-vampire-128",
    "mtgcards.serra-angel-40",
    "mtgcards.simulacrum-129",
    "mtgcards.sirens-call-78",
    "mtgcards.sol-ring-270",
    "mtgcards.soul-net-271",
    "mtgcards.steal-artifact-82",
    "mtgcards.stone-giant-177",
    "mtgcards.swords-to-plowshares-41",
    "mtgcards.thicket-basilisk-219",
    "mtgcards.throne-of-bone-274",
    "mtgcards.tsunami-222",
    "mtgcards.tunnel-179",
    "mtgcards.uthden-troll-181",
    "mtgcards.wall-of-air-90",
    "mtgcards.wall-of-bone-133",
    "mtgcards.wall-of-brambles-224",
    "mtgcards.wall-of-fire-182",
    "mtgcards.wall-of-ice-225",
    "mtgcards.wall-of-stone-183",
    "mtgcards.wall-of-swords-43",
    "mtgcards.wall-of-water-91",
    "mtgcards.wanderlust-227",
    "mtgcards.water-elemental-92",
    "mtgcards.white-knight-44",
    "mtgcards.white-ward-45",
    "mtgcards.wooden-sphere-277",
}

beta_r = {
    "mtgcards.ancestral-recall-48",
    "mtgcards.animate-wall-1",
    "mtgcards.ankh-of-mishra-231",
    "mtgcards.armageddon-2",
    "mtgcards.aspect-of-wolf-185",
    "mtgcards.badlands-278",
    "mtgcards.bad-moon-94",
    "mtgcards.balance-3",
    "mtgcards.bayou-279",
    "mtgcards.birds-of-paradise-187",
    "mtgcards.black-lotus-233",
    "mtgcards.blaze-of-glory-6",
    "mtgcards.blessing-7",
    "mtgcards.braingeyser-51",
    "mtgcards.chaoslace-140",
    "mtgcards.chaos-orb-236",
    "mtgcards.clockwork-beast-237",
    "mtgcards.cockatrice-190",
    "mtgcards.contract-from-below-97",
    "mtgcards.copy-artifact-54",
    "mtgcards.crusade-17",
    "mtgcards.cyclopean-tomb-241",
    "mtgcards.darkpact-100",
    "mtgcards.deathlace-102",
    "mtgcards.demonic-attorney-103",
    "mtgcards.demonic-hordes-104",
    "mtgcards.dingus-egg-242",
    "mtgcards.disrupting-scepter-243",
    "mtgcards.drain-power-57",
    "mtgcards.earthquake-147",
    "mtgcards.elvish-archers-192",
    "mtgcards.farmstead-20",
    "mtgcards.fastbond-193",
    "mtgcards.forcefield-244",
    "mtgcards.force-of-nature-195",
    "mtgcards.fork-153",
    "mtgcards.fungusaur-196",
    "mtgcards.gaeas-liege-197",
    "mtgcards.gauntlet-of-might-245",
    "mtgcards.goblin-king-155",
    "mtgcards.granite-gargoyle-156",
    "mtgcards.helm-of-chatzuk-247",
    "mtgcards.howling-mine-248",
    "mtgcards.illusionary-mask-250",
    "mtgcards.island-sanctuary-26",
    "mtgcards.jade-monolith-253",
    "mtgcards.jayemdae-tome-255",
    "mtgcards.kormus-bell-257",
    "mtgcards.kudzu-205",
    "mtgcards.lich-114",
    "mtgcards.lifelace-208",
    "mtgcards.living-artifact-209",
    "mtgcards.living-lands-210",
    "mtgcards.lord-of-atlantis-63",
    "mtgcards.lord-of-the-pit-115",
    "mtgcards.magical-hack-64",
    "mtgcards.mahamoti-djinn-65",
    "mtgcards.manabarbs-164",
    "mtgcards.mana-flare-163",
    "mtgcards.mana-short-66",
    "mtgcards.mana-vault-260",
    "mtgcards.meekstone-261",
    "mtgcards.mind-twist-116",
    "mtgcards.mox-emerald-262",
    "mtgcards.mox-jet-263",
    "mtgcards.mox-pearl-264",
    "mtgcards.mox-ruby-265",
    "mtgcards.mox-sapphire-266",
    "mtgcards.natural-selection-213",
    "mtgcards.nether-shadow-117",
    "mtgcards.nevinyrrals-disk-267",
    "mtgcards.nightmare-119",
    "mtgcards.northern-paladin-30",
    "mtgcards.personal-incarnation-32",
    "mtgcards.pirate-ship-71",
    "mtgcards.plateau-280",
    "mtgcards.power-surge-168",
    "mtgcards.purelace-33",
    "mtgcards.raging-river-169",
    "mtgcards.reverse-damage-36",
    "mtgcards.righteousness-37",
    "mtgcards.rock-hydra-172",
    "mtgcards.roc-of-kher-ridges-171",
    "mtgcards.royal-assassin-124",
    "mtgcards.savannah-281",
    "mtgcards.savannah-lions-39",
    "mtgcards.scrubland-282",
    "mtgcards.sedge-troll-173",
    "mtgcards.shivan-dragon-175",
    "mtgcards.sleight-of-mind-79",
    "mtgcards.smoke-176",
    "mtgcards.stasis-81",
    "mtgcards.sunglasses-of-urza-272",
    "mtgcards.taiga-283",
    "mtgcards.the-hive-273",
    "mtgcards.thoughtlace-83",
    "mtgcards.timber-wolves-220",
    "mtgcards.timetwister-85",
    "mtgcards.time-vault-275",
    "mtgcards.time-walk-84",
    "mtgcards.tropical-island-284",
    "mtgcards.tundra-285",
    "mtgcards.two-headed-giant-of-foriys-180",
    "mtgcards.underground-sea-286",
    "mtgcards.verduran-enchantress-223",
    "mtgcards.vesuvan-doppelganger-88",
    "mtgcards.veteran-bodyguard-42",
    "mtgcards.volcanic-eruption-89",
    "mtgcards.volcanic-island-287",
    "mtgcards.warp-artifact-134",
    "mtgcards.web-229",
    "mtgcards.wheel-of-fortune-184",
    "mtgcards.will-o-the-wisp-136",
    "mtgcards.winter-orb-276",
    "mtgcards.word-of-command-137",
    "mtgcards.wrath-of-god-46",
    "mtgcards.zombie-master-138",
}

beta_lands = {
    "mtgcards.forest-300",
    "mtgcards.forest-301",
    "mtgcards.forest-302",
    "mtgcards.island-291",
    "mtgcards.island-292",
    "mtgcards.island-293",
    "mtgcards.mountain-297",
    "mtgcards.mountain-298",
    "mtgcards.mountain-299",
    "mtgcards.plains-288",
    "mtgcards.plains-289",
    "mtgcards.plains-290",
    "mtgcards.swamp-294",
    "mtgcards.swamp-295",
    "mtgcards.swamp-296",
}

-- Display names mapping
mtgCardDisplayNames = {
    ["air-elemental-47"] = "Air Elemental",
    ["ancestral-recall-48"] = "Ancestral Recall",
    ["animate-artifact-49"] = "Animate Artifact",
    ["animate-dead-93"] = "Animate Dead",
    ["animate-wall-1"] = "Animate Wall",
    ["ankh-of-mishra-231"] = "Ankh of Mishra",
    ["armageddon-2"] = "Armageddon",
    ["aspect-of-wolf-185"] = "Aspect of Wolf",
    ["bad-moon-94"] = "Bad Moon",
    ["badlands-278"] = "Badlands",
    ["balance-3"] = "Balance",
    ["basalt-monolith-232"] = "Basalt Monolith",
    ["bayou-279"] = "Bayou",
    ["benalish-hero-4"] = "Benalish Hero",
    ["berserk-186"] = "Berserk",
    ["birds-of-paradise-187"] = "Birds of Paradise",
    ["black-knight-95"] = "Black Knight",
    ["black-lotus-233"] = "Black Lotus",
    ["black-vise-234"] = "Black Vise",
    ["black-ward-5"] = "Black Ward",
    ["blaze-of-glory-6"] = "Blaze of Glory",
    ["blessing-7"] = "Blessing",
    ["blue-elemental-blast-50"] = "Blue Elemental Blast",
    ["blue-ward-8"] = "Blue Ward",
    ["bog-wraith-96"] = "Bog Wraith",
    ["braingeyser-51"] = "Braingeyser",
    ["burrowing-139"] = "Burrowing",
    ["camouflage-188"] = "Camouflage",
    ["castle-9"] = "Castle",
    ["celestial-prism-235"] = "Celestial Prism",
    ["channel-189"] = "Channel",
    ["chaos-orb-236"] = "Chaos Orb",
    ["chaoslace-140"] = "Chaoslace",
    ["circle-of-protection-black-10"] = "Circle of Protection: Black",
    ["circle-of-protection-blue-11"] = "Circle of Protection: Blue",
    ["circle-of-protection-green-12"] = "Circle of Protection: Green",
    ["circle-of-protection-red-13"] = "Circle of Protection: Red",
    ["circle-of-protection-white-14"] = "Circle of Protection: White",
    ["clockwork-beast-237"] = "Clockwork Beast",
    ["clone-52"] = "Clone",
    ["cockatrice-190"] = "Cockatrice",
    ["consecrate-land-15"] = "Consecrate Land",
    ["conservator-238"] = "Conservator",
    ["contract-from-below-97"] = "Contract from Below",
    ["control-magic-53"] = "Control Magic",
    ["conversion-16"] = "Conversion",
    ["copper-tablet-239"] = "Copper Tablet",
    ["copy-artifact-54"] = "Copy Artifact",
    ["counterspell-55"] = "Counterspell",
    ["craw-wurm-191"] = "Craw Wurm",
    ["creature-bond-56"] = "Creature Bond",
    ["crusade-17"] = "Crusade",
    ["crystal-rod-240"] = "Crystal Rod",
    ["cursed-land-98"] = "Cursed Land",
    ["cyclopean-tomb-241"] = "Cyclopean Tomb",
    ["dark-ritual-99"] = "Dark Ritual",
    ["darkpact-100"] = "Darkpact",
    ["death-ward-18"] = "Death Ward",
    ["deathgrip-101"] = "Deathgrip",
    ["deathlace-102"] = "Deathlace",
    ["demonic-attorney-103"] = "Demonic Attorney",
    ["demonic-hordes-104"] = "Demonic Hordes",
    ["demonic-tutor-105"] = "Demonic Tutor",
    ["dingus-egg-242"] = "Dingus Egg",
    ["disenchant-19"] = "Disenchant",
    ["disintegrate-141"] = "Disintegrate",
    ["disrupting-scepter-243"] = "Disrupting Scepter",
    ["dragon-whelp-142"] = "Dragon Whelp",
    ["drain-life-106"] = "Drain Life",
    ["drain-power-57"] = "Drain Power",
    ["drudge-skeletons-107"] = "Drudge Skeletons",
    ["dwarven-demolition-team-143"] = "Dwarven Demolition Team",
    ["dwarven-warriors-144"] = "Dwarven Warriors",
    ["earth-elemental-145"] = "Earth Elemental",
    ["earthbind-146"] = "Earthbind",
    ["earthquake-147"] = "Earthquake",
    ["elvish-archers-192"] = "Elvish Archers",
    ["evil-presence-108"] = "Evil Presence",
    ["false-orders-148"] = "False Orders",
    ["farmstead-20"] = "Farmstead",
    ["fastbond-193"] = "Fastbond",
    ["fear-109"] = "Fear",
    ["feedback-58"] = "Feedback",
    ["fire-elemental-149"] = "Fire Elemental",
    ["fireball-150"] = "Fireball",
    ["firebreathing-151"] = "Firebreathing",
    ["flashfires-152"] = "Flashfires",
    ["flight-59"] = "Flight",
    ["fog-194"] = "Fog",
    ["force-of-nature-195"] = "Force of Nature",
    ["forcefield-244"] = "Forcefield",
    ["forest-300"] = "Forest",
    ["forest-301"] = "Forest",
    ["forest-302"] = "Forest",
    ["fork-153"] = "Fork",
    ["frozen-shade-110"] = "Frozen Shade",
    ["fungusaur-196"] = "Fungusaur",
    ["gaeas-liege-197"] = "Gaea's Liege",
    ["gauntlet-of-might-245"] = "Gauntlet of Might",
    ["giant-growth-198"] = "Giant Growth",
    ["giant-spider-199"] = "Giant Spider",
    ["glasses-of-urza-246"] = "Glasses of Urza",
    ["gloom-111"] = "Gloom",
    ["goblin-balloon-brigade-154"] = "Goblin Balloon Brigade",
    ["goblin-king-155"] = "Goblin King",
    ["granite-gargoyle-156"] = "Granite Gargoyle",
    ["gray-ogre-157"] = "Gray Ogre",
    ["green-ward-21"] = "Green Ward",
    ["grizzly-bears-200"] = "Grizzly Bears",
    ["guardian-angel-22"] = "Guardian Angel",
    ["healing-salve-23"] = "Healing Salve",
    ["helm-of-chatzuk-247"] = "Helm of Chatzuk",
    ["hill-giant-158"] = "Hill Giant",
    ["holy-armor-24"] = "Holy Armor",
    ["holy-strength-25"] = "Holy Strength",
    ["howl-from-beyond-112"] = "Howl from Beyond",
    ["howling-mine-248"] = "Howling Mine",
    ["hurloon-minotaur-159"] = "Hurloon Minotaur",
    ["hurricane-201"] = "Hurricane",
    ["hypnotic-specter-113"] = "Hypnotic Specter",
    ["ice-storm-202"] = "Ice Storm",
    ["icy-manipulator-249"] = "Icy Manipulator",
    ["illusionary-mask-250"] = "Illusionary Mask",
    ["instill-energy-203"] = "Instill Energy",
    ["invisibility-60"] = "Invisibility",
    ["iron-star-251"] = "Iron Star",
    ["ironclaw-orcs-160"] = "Ironclaw Orcs",
    ["ironroot-treefolk-204"] = "Ironroot Treefolk",
    ["island-291"] = "Island",
    ["island-292"] = "Island",
    ["island-293"] = "Island",
    ["island-sanctuary-26"] = "Island Sanctuary",
    ["ivory-cup-252"] = "Ivory Cup",
    ["jade-monolith-253"] = "Jade Monolith",
    ["jade-statue-254"] = "Jade Statue",
    ["jayemdae-tome-255"] = "Jayemdae Tome",
    ["juggernaut-256"] = "Juggernaut",
    ["jump-61"] = "Jump",
    ["karma-27"] = "Karma",
    ["keldon-warlord-161"] = "Keldon Warlord",
    ["kormus-bell-257"] = "Kormus Bell",
    ["kudzu-205"] = "Kudzu",
    ["lance-28"] = "Lance",
    ["ley-druid-206"] = "Ley Druid",
    ["library-of-leng-258"] = "Library of Leng",
    ["lich-114"] = "Lich",
    ["lifeforce-207"] = "Lifeforce",
    ["lifelace-208"] = "Lifelace",
    ["lifetap-62"] = "Lifetap",
    ["lightning-bolt-162"] = "Lightning Bolt",
    ["living-artifact-209"] = "Living Artifact",
    ["living-lands-210"] = "Living Lands",
    ["living-wall-259"] = "Living Wall",
    ["llanowar-elves-211"] = "Llanowar Elves",
    ["lord-of-atlantis-63"] = "Lord of Atlantis",
    ["lord-of-the-pit-115"] = "Lord of the Pit",
    ["lure-212"] = "Lure",
    ["magical-hack-64"] = "Magical Hack",
    ["mahamoti-djinn-65"] = "Mahamoti Djinn",
    ["mana-flare-163"] = "Mana Flare",
    ["mana-short-66"] = "Mana Short",
    ["mana-vault-260"] = "Mana Vault",
    ["manabarbs-164"] = "Manabarbs",
    ["meekstone-261"] = "Meekstone",
    ["merfolk-of-the-pearl-trident-67"] = "Merfolk of the Pearl Trident",
    ["mesa-pegasus-29"] = "Mesa Pegasus",
    ["mind-twist-116"] = "Mind Twist",
    ["monss-goblin-raiders-165"] = "Mons's Goblin Raiders",
    ["mountain-297"] = "Mountain",
    ["mountain-298"] = "Mountain",
    ["mountain-299"] = "Mountain",
    ["mox-emerald-262"] = "Mox Emerald",
    ["mox-jet-263"] = "Mox Jet",
    ["mox-pearl-264"] = "Mox Pearl",
    ["mox-ruby-265"] = "Mox Ruby",
    ["mox-sapphire-266"] = "Mox Sapphire",
    ["natural-selection-213"] = "Natural Selection",
    ["nether-shadow-117"] = "Nether Shadow",
    ["nettling-imp-118"] = "Nettling Imp",
    ["nevinyrrals-disk-267"] = "Nevinyrral's Disk",
    ["nightmare-119"] = "Nightmare",
    ["northern-paladin-30"] = "Northern Paladin",
    ["obsianus-golem-268"] = "Obsianus Golem",
    ["orcish-artillery-166"] = "Orcish Artillery",
    ["orcish-oriflamme-167"] = "Orcish Oriflamme",
    ["paralyze-120"] = "Paralyze",
    ["pearled-unicorn-31"] = "Pearled Unicorn",
    ["personal-incarnation-32"] = "Personal Incarnation",
    ["pestilence-121"] = "Pestilence",
    ["phantasmal-forces-68"] = "Phantasmal Forces",
    ["phantasmal-terrain-69"] = "Phantasmal Terrain",
    ["phantom-monster-70"] = "Phantom Monster",
    ["pirate-ship-71"] = "Pirate Ship",
    ["plague-rats-122"] = "Plague Rats",
    ["plains-288"] = "Plains",
    ["plains-289"] = "Plains",
    ["plains-290"] = "Plains",
    ["plateau-280"] = "Plateau",
    ["power-leak-72"] = "Power Leak",
    ["power-sink-73"] = "Power Sink",
    ["power-surge-168"] = "Power Surge",
    ["prodigal-sorcerer-74"] = "Prodigal Sorcerer",
    ["psionic-blast-75"] = "Psionic Blast",
    ["psychic-venom-76"] = "Psychic Venom",
    ["purelace-33"] = "Purelace",
    ["raging-river-169"] = "Raging River",
    ["raise-dead-123"] = "Raise Dead",
    ["red-elemental-blast-170"] = "Red Elemental Blast",
    ["red-ward-34"] = "Red Ward",
    ["regeneration-214"] = "Regeneration",
    ["regrowth-215"] = "Regrowth",
    ["resurrection-35"] = "Resurrection",
    ["reverse-damage-36"] = "Reverse Damage",
    ["righteousness-37"] = "Righteousness",
    ["roc-of-kher-ridges-171"] = "Roc of Kher Ridges",
    ["rock-hydra-172"] = "Rock Hydra",
    ["rod-of-ruin-269"] = "Rod of Ruin",
    ["royal-assassin-124"] = "Royal Assassin",
    ["sacrifice-125"] = "Sacrifice",
    ["samite-healer-38"] = "Samite Healer",
    ["savannah-281"] = "Savannah",
    ["savannah-lions-39"] = "Savannah Lions",
    ["scathe-zombies-126"] = "Scathe Zombies",
    ["scavenging-ghoul-127"] = "Scavenging Ghoul",
    ["scrubland-282"] = "Scrubland",
    ["scryb-sprites-216"] = "Scryb Sprites",
    ["sea-serpent-77"] = "Sea Serpent",
    ["sedge-troll-173"] = "Sedge Troll",
    ["sengir-vampire-128"] = "Sengir Vampire",
    ["serra-angel-40"] = "Serra Angel",
    ["shanodin-dryads-217"] = "Shanodin Dryads",
    ["shatter-174"] = "Shatter",
    ["shivan-dragon-175"] = "Shivan Dragon",
    ["simulacrum-129"] = "Simulacrum",
    ["sinkhole-130"] = "Sinkhole",
    ["sirens-call-78"] = "Siren's Call",
    ["sleight-of-mind-79"] = "Sleight of Mind",
    ["smoke-176"] = "Smoke",
    ["sol-ring-270"] = "Sol Ring",
    ["soul-net-271"] = "Soul Net",
    ["spell-blast-80"] = "Spell Blast",
    ["stasis-81"] = "Stasis",
    ["steal-artifact-82"] = "Steal Artifact",
    ["stone-giant-177"] = "Stone Giant",
    ["stone-rain-178"] = "Stone Rain",
    ["stream-of-life-218"] = "Stream of Life",
    ["sunglasses-of-urza-272"] = "Sunglasses of Urza",
    ["swamp-294"] = "Swamp",
    ["swamp-295"] = "Swamp",
    ["swamp-296"] = "Swamp",
    ["swords-to-plowshares-41"] = "Swords to Plowshares",
    ["taiga-283"] = "Taiga",
    ["terror-131"] = "Terror",
    ["the-hive-273"] = "The Hive",
    ["thicket-basilisk-219"] = "Thicket Basilisk",
    ["thoughtlace-83"] = "Thoughtlace",
    ["throne-of-bone-274"] = "Throne of Bone",
    ["timber-wolves-220"] = "Timber Wolves",
    ["time-vault-275"] = "Time Vault",
    ["time-walk-84"] = "Time Walk",
    ["timetwister-85"] = "Timetwister",
    ["tranquility-221"] = "Tranquility",
    ["tropical-island-284"] = "Tropical Island",
    ["tsunami-222"] = "Tsunami",
    ["tundra-285"] = "Tundra",
    ["tunnel-179"] = "Tunnel",
    ["twiddle-86"] = "Twiddle",
    ["two-headed-giant-of-foriys-180"] = "Two-Headed Giant of Foriys",
    ["underground-sea-286"] = "Underground Sea",
    ["unholy-strength-132"] = "Unholy Strength",
    ["unsummon-87"] = "Unsummon",
    ["uthden-troll-181"] = "Uthden Troll",
    ["verduran-enchantress-223"] = "Verduran Enchantress",
    ["vesuvan-doppelganger-88"] = "Vesuvan Doppelganger",
    ["veteran-bodyguard-42"] = "Veteran Bodyguard",
    ["volcanic-eruption-89"] = "Volcanic Eruption",
    ["volcanic-island-287"] = "Volcanic Island",
    ["wall-of-air-90"] = "Wall of Air",
    ["wall-of-bone-133"] = "Wall of Bone",
    ["wall-of-brambles-224"] = "Wall of Brambles",
    ["wall-of-fire-182"] = "Wall of Fire",
    ["wall-of-ice-225"] = "Wall of Ice",
    ["wall-of-stone-183"] = "Wall of Stone",
    ["wall-of-swords-43"] = "Wall of Swords",
    ["wall-of-water-91"] = "Wall of Water",
    ["wall-of-wood-226"] = "Wall of Wood",
    ["wanderlust-227"] = "Wanderlust",
    ["war-mammoth-228"] = "War Mammoth",
    ["warp-artifact-134"] = "Warp Artifact",
    ["water-elemental-92"] = "Water Elemental",
    ["weakness-135"] = "Weakness",
    ["web-229"] = "Web",
    ["wheel-of-fortune-184"] = "Wheel of Fortune",
    ["white-knight-44"] = "White Knight",
    ["white-ward-45"] = "White Ward",
    ["wild-growth-230"] = "Wild Growth",
    ["will-o-the-wisp-136"] = "Will-o'-the-Wisp",
    ["winter-orb-276"] = "Winter Orb",
    ["wooden-sphere-277"] = "Wooden Sphere",
    ["word-of-command-137"] = "Word of Command",
    ["wrath-of-god-46"] = "Wrath of God",
    ["zombie-master-138"] = "Zombie Master",
}

-- Stats: 75 commons, 95 uncommons, 117 rares, 15 lands
-- Total: 302 cards
